import codecs
import re
import string

regexp = re.compile ('\{\{|\}\}')

def process_line (line, short_opts, long_opts):
    reassembled = []
    pieces = regexp.split (line)
    if pieces != None:
        for piece in pieces:
            if piece.startswith ('--'):
                long_opts.append (string.replace (piece, '-', ''))
            elif piece.startswith ('-'):
                short_opts.append(string.replace (piece, '-', ''))
            reassembled.append (piece)
    return ''.join (reassembled)

instream=codecs.open('help-template.txt', 'r', 'utf-8')

short_opts = []
long_opts = []

print "# THIS FILE IS AUTOGENERATED"
print
print 'def print_help ():'
for line in instream:
    processed_line = process_line (line.rstrip (), short_opts, long_opts)
    if len (processed_line.strip()) > 0:
        print "    print '" + processed_line + "'"
    else:
        print "    print"

print
print "SHORT_OPTS = '" + ''.join(short_opts) + "'" 
print "LONG_OPTS = ['" + "','".join(long_opts) + "']" 
  
instream.close ()