# THIS FILE IS AUTOGENERATED

def print_help ():
    print 'Version 1.0.5 (2013-04-18)'
    print
    print 'Usage:'
    print
    print 'ofexport [options...] -o file_name'
    print
    print
    print 'options:'
    print '  -h,-?,--help'
    print '  -C: context mode (as opposed to project mode)'
    print '  -P: project mode - the default (as opposed to context mode)'
    print '  -l: print links to tasks (in supported file formats)'
    print '  -o: file_name: the output file name, must end in a recognised suffix - see documentation'
    print '  -i: file_name: read file_name instead of the OmniFocus database, must be in json format'
    print '  --open: open the output file with the registered application (if one is installed)'
    print
    print 'filters:'
    print '  -a:,--any=     filter tasks, projects, contexts and folders against argument'
    print '  -t:,--task=    filter any task against task against argument'
    print '  -p:,--project= filter any project against argument'
    print '  -f:,--folder=  filter any folder against argument'
    print '  -c:,--context= filter any context type against argument'
    print
    print '  A filter argument may be:'
    print '    text=regexp'
    print '    text!=regexp'
    print '    =regexp (abbrieviation of text=regexp)'
    print '    !=regexp (abbrieviation of text!=regexp)'
    print '    flagged'
    print '    !flagged'
    print '    due=tomorrow'
    print '    start!=this week (this will need quoting on the command line, because of the space)'
    print '    sort=completed'
    print '    prune'
    print '    flatten'
    print
    print '  See DOCUMENTATION.md for more information'

SHORT_OPTS = 'h?CPlo:i:a:t:p:f:c:'
LONG_OPTS = ['help','open','any=','task=','project=','folder=','context=']
