#!/bin/bash

####################
# Run all the tests.
#
# If run with an argument then that argument is expected
# to be a file format and the tool tests are run in
# that format alone
####################

# set -o xtrace
set -e
export PYTHONPATH=`pwd`

################
# Run unit tests
################

cd tests
rm *.pyc
for FILE in $( ls ); do
        MODULE=`echo $FILE | sed -e 's/\.py$//'`
        echo module: $MODULE
        python -m unittest -f -v $MODULE
done
cd ..

#########################################################
# Run some tests against a test folder in my OmniFocus DB
#########################################################

rm *.pyc

TEST_FOLDER="^Home$"
TEST_CONTEXT="\+Times$"


function run_tool {

    FMT=$1
    MODE=$2
    
	set +e
	mkdir -p tmp/$FMT
	set -e
	
	for TYPE in -t -f -p -c; do
	
	    # Be nice to my cpu fans...
        sleep 1; nice -20 python ofexport.py -o tmp/$FMT/01$MODE$TYPE.$FMT $MODE -f="$TEST_FOLDER"
        sleep 1; nice -20 python ofexport.py -o tmp/$FMT/02$MODE$TYPE.$FMT $MODE -f="$TEST_FOLDER" $TYPE=a
        sleep 1; nice -20 python ofexport.py -o tmp/$FMT/03$MODE$TYPE.$FMT $MODE -f="$TEST_FOLDER" $TYPE!=a
        sleep 1; nice -20 python ofexport.py -o tmp/$FMT/04$MODE$TYPE.$FMT $MODE -f="$TEST_FOLDER" $TYPE done="this week"
        sleep 1; nice -20 python ofexport.py -o tmp/$FMT/05$MODE$TYPE.$FMT $MODE -f="$TEST_FOLDER" $TYPE done!="this week"
        sleep 1; nice -20 python ofexport.py -o tmp/$FMT/06$MODE$TYPE.$FMT $MODE -f="$TEST_FOLDER" $TYPE due="this week"
        sleep 1; nice -20 python ofexport.py -o tmp/$FMT/07$MODE$TYPE.$FMT $MODE -f="$TEST_FOLDER" $TYPE due!="this week"
        sleep 1; nice -20 python ofexport.py -o tmp/$FMT/08$MODE$TYPE.$FMT $MODE -f="$TEST_FOLDER" $TYPE completed="this week"
        sleep 1; nice -20 python ofexport.py -o tmp/$FMT/09$MODE$TYPE.$FMT $MODE -f="$TEST_FOLDER" $TYPE completed!="this week"
        sleep 1; nice -20 python ofexport.py -o tmp/$FMT/10$MODE$TYPE.$FMT $MODE -f="$TEST_FOLDER" $TYPE start="this week"
        sleep 1; nice -20 python ofexport.py -o tmp/$FMT/11$MODE$TYPE.$FMT $MODE -f="$TEST_FOLDER" $TYPE start!="this week"
        sleep 1; nice -20 python ofexport.py -o tmp/$FMT/12$MODE$TYPE.$FMT $MODE -f="$TEST_FOLDER" $TYPE done="this week"
        sleep 1; nice -20 python ofexport.py -o tmp/$FMT/13$MODE$TYPE.$FMT $MODE -f="$TEST_FOLDER" $TYPE done!="this week"
        sleep 1; nice -20 python ofexport.py -o tmp/$FMT/14$MODE$TYPE.$FMT $MODE -f="$TEST_FOLDER" $TYPE due="this week"
        sleep 1; nice -20 python ofexport.py -o tmp/$FMT/15$MODE$TYPE.$FMT $MODE -f="$TEST_FOLDER" $TYPE due!="this week"
        sleep 1; nice -20 python ofexport.py -o tmp/$FMT/16$MODE$TYPE.$FMT $MODE -f="$TEST_FOLDER" $TYPE flagged
        sleep 1; nice -20 python ofexport.py -o tmp/$FMT/17$MODE$TYPE.$FMT $MODE -f="$TEST_FOLDER" $TYPE !flagged
        sleep 1; nice -20 python ofexport.py -o tmp/$FMT/18$MODE$TYPE.$FMT $MODE -f="$TEST_FOLDER" $TYPE sort
        sleep 1; nice -20 python ofexport.py -o tmp/$FMT/19$MODE$TYPE.$FMT $MODE -f="$TEST_FOLDER" $TYPE sort=start
        sleep 1; nice -20 python ofexport.py -o tmp/$FMT/20$MODE$TYPE.$FMT $MODE -f="$TEST_FOLDER" $TYPE sort=due
        sleep 1; nice -20 python ofexport.py -o tmp/$FMT/21$MODE$TYPE.$FMT $MODE -f="$TEST_FOLDER" $TYPE sort=completed
        sleep 1; nice -20 python ofexport.py -o tmp/$FMT/22$MODE$TYPE.$FMT $MODE -f="$TEST_FOLDER" $TYPE prune
        sleep 1; nice -20 python ofexport.py -o tmp/$FMT/23$MODE$TYPE.$FMT $MODE -f="$TEST_FOLDER" $TYPE flat
        
    done
	
}

FMT=$1

if [ -z "$FMT" ]; then
    for FMT in tp md html opml ft; do
        for MODE in -P -C; do
            run_tool $FMT $MODE
        done
    done
else
    run_tool $FMT -P
    run_tool $FMT -C
fi