# THIS FILE IS AUTOGENERATED

def print_help ():
    print 'Version: 1.1.1-SNAPSHOT 2013-04-28'
    print
    print 'Usage:'
    print
    print 'ofexport [options...] -o file_name'
    print
    print 'options:'
    print '  -h,-?,--help       : print help'
    print '  -C                 : context mode (as opposed to project mode)'
    print '  -P                 : project mode - the default (as opposed to context mode)'
    print '  -I                 : include mode (as opposed to exclude mode)'
    print '  -E                 : exclude mode - the default (as opposed to include mode)'
    print '  -v                 : verbose output'
    print '  -o file_name       : the output file name, must end in a recognised suffix - see documentation'
    print '  -i file_name       : read file_name instead of the OmniFocus database, must be in json format'
    print '  -T - template_name : use the specified template instead of one derived from the output file extension'
    print '  --open             : open the output file with the registered application (if one is installed)'
    print '  --log name=level   : set a logger to a particular level'
    print
    print 'filters:'
    print '  -a,--any expr        : filter tasks, projects, contexts and folders against the expression'
    print '  -t,--task expr       : filter any task against task against the expression'
    print '  -p,--project expr    : filter any project against the expression'
    print '  -f,--folder  expr    : filter any folder against the expression'
    print '  -c,--context expr    : filter any context type against the expression'
    print
    print '  See DOCUMENTATION.md for more information'

SHORT_OPTS = 'h?CPIEvo:i:T:a:t:p:f:c:'
LONG_OPTS = ['help','open','log=','any=','task=','project=','folder=','context=']
