#!/bin/bash
set -e
#C This file contains the examples as tests an then creates the examples.md file from itself
#C Lines beginning with "set", "diff", '#!', '#C' are ignored
#C Lines beginning with '#' have the # removed

## Usage Examples

#C ofexport -f='^Test' -C -c="^Test" -o src/test/data/db-5.json

#This produces a document containing all tasks completed last week from any folder with "Worms" in it's title:
    
        ofexport -f=Worms -t "done='last week'" -a prune -o target/ex1-worms-last-week.taskpaper --debug now=2013-04-29 -i src/test/data/db-5.json
diff target/ex1-worms-last-week.taskpaper src/test/data/ex1-worms-last-week.taskpaper

#This uses a little regular expression magic to create a document containing all tasks completed today from any folder with the exact name "Ham":
    
        ofexport -f='^Ham$' -t done='today' -a prune -o target/ex2-ham-today.taskpaper --debug now=2013-04-29 -i src/test/data/db-5.json
diff target/ex2-ham-today.taskpaper src/test/data/ex2-ham-today.taskpaper
   
#This produces a document containing all tasks completed today from any folder that does NOT have "Worms" in it's title:
    
        ofexport -E -f=Worms -a prune -o target/ex3-not-worms.taskpaper --debug now=2013-04-29 -i src/test/data/db-5.json
diff target/ex3-not-worms.taskpaper src/test/data/ex3-not-worms.taskpaper

#This uses a little regular expression magic to create a document containing all tasks completed today from any folder with the exact name "Worms" or "Ham":
    
        ofexport -f='^Worms$|^Ham$' -t done='today' -a prune -o target/ex4-worms-or-ham-today.taskpaper --debug now=2013-04-29
diff target/ex4-worms-or-ham-today.taskpaper src/test/data/ex4-worms-or-ham-today.taskpaper

#This produces a document containing all tasks completed this week from any folder with "Worms" in it's title and then flattens/simplifies the indenting:
    
        ofexport -f=Worms -a flatten -a prune -o target/ex5-work-this-week-flat.taskpaper --debug now=2013-04-29
diff target/ex5-work-this-week-flat.taskpaper src/test/data/ex5-work-this-week-flat.taskpaper

#This produces the report of what I have yet to do on this project           

        ofexport -o TODO.md -f='"ofexport"' -f flatten -a prune -E -t done=any

#This produces the report of all uncompleted tasks that are flagged or due soon

        ofexport -E -a done=any -I -t "flagged or (due='to tomorrow')" -o target/ex8-due-or-flagged.taskpaper --debug now=2013-04-29 -i src/test/data/db-5.json
diff target/ex8-due-or-flagged.taskpaper src/test/data/ex8-due-or-flagged.taskpaper

cat build-scripts/examples | egrep -v -e '^cat|^diff|^#C|^#!' -e '^set' | sed -e 's/^#//' -e 's/--debug.*//' -e 's/target/\/tmp/' > documentation/examples.md

