#!/bin/bash

#set -o xtrace
set -e
export PYTHONPATH=`pwd`/src/main/python

mkdir target

################
echo -- HELP
################
#ofexport --log ofexport=ERROR | sed -e 's/^Version: [0-9].*/Version: XXX XXX/' > src/test/data/help.txt
ofexport --log ofexport=ERROR -? | sed -e 's/^Version: [0-9].*/Version: XXX XXX/' > target/help.txt
diff src/test/data/help.txt target/help.txt
ofexport --log ofexport=ERROR -h | sed -e 's/^Version: [0-9].*/Version: XXX XXX/' > target/help.txt
diff src/test/data/help.txt target/help.txt
ofexport --log ofexport=ERROR --help | sed -e 's/^Version: [0-9].*/Version: XXX XXX/' > target/help.txt
diff src/test/data/help.txt target/help.txt


#build-scripts/dump-test-data --open -o src/test/data/db-1.json

#---------------------------------------------------------------------

################
echo FORMAT TESTS - Project
################

for FMT in taskpaper md html opml ft json text; do

    ################
    echo -- $FMT
    ################
    #ofexport --log ofexport=ERROR -i src/test/data/db-1.json -o src/test/data/db-1.$FMT
    ofexport --log ofexport=ERROR -i src/test/data/db-1.json -o target/db-1.$FMT
    diff src/test/data/db-1.$FMT target/db-1.$FMT

done

################
echo FORMAT TESTS - Context
################

for FMT in taskpaper md html opml ft json; do

    ################
    echo -- $FMT
    ################
    #ofexport --log ofexport=ERROR -i src/test/data/db-1.json -C -o src/test/data/db-1-C.$FMT
    ofexport --log ofexport=ERROR -i src/test/data/db-1.json -C -o target/db-1-C.$FMT
    diff src/test/data/db-1-C.$FMT target/db-1-C.$FMT

done

# Empty project should appear in context mode
FMT=taskpaper
#ofexport --log ofexport=ERROR --open -i src/test/data/db-2.json -o src/test/data/db-2-C.$FMT
ofexport --log ofexport=ERROR -i src/test/data/db-2.json -o target/db-2-C.$FMT
diff src/test/data/db-2-C.$FMT target/db-2-C.$FMT

################
echo FORMAT TESTS - extra templates
################

FMT=taskpaper
################
echo -- $FMT
################
#ofexport --log ofexport=ERROR -i src/test/data/db-1.json -T taskpaper-lite -o src/test/data/db-1-taskpaper-lite.$FMT
ofexport --log ofexport=ERROR -i src/test/data/db-1.json -T taskpaper-lite -o target/db-1-taskpaper-lite.$FMT
diff src/test/data/db-1-taskpaper-lite.$FMT target/db-1-taskpaper-lite.$FMT

FMT=html
################
echo -- $FMT
################
#ofexport --log ofexport=ERROR -i src/test/data/db-1.json -T html-lite -o src/test/data/db-1-html-lite.$FMT
ofexport --log ofexport=ERROR -i src/test/data/db-1.json -T html-lite -o target/db-1-html-lite.$FMT
diff src/test/data/db-1-html-lite.$FMT target/db-1-html-lite.$FMT
#---------------------------------------------------------------------

################
echo FLATTENING TESTS
################

for TYPE in Task Folder; do

    ################
    echo -- $TYPE
    ################
    #ofexport --log ofexport=ERROR --open -i src/test/data/db-3.json -o src/test/data/db-3-$TYPE-flatten.taskpaper -a "flatten $TYPE"
    ofexport --log ofexport=ERROR -i src/test/data/db-3.json -o target/db-3-$TYPE-flatten.taskpaper -a "flatten $TYPE"
    diff src/test/data/db-3-$TYPE-flatten.taskpaper target/db-3-$TYPE-flatten.taskpaper

done

TYPE=Context
################
echo -- $TYPE
################
#ofexport --log ofexport=ERROR --open -i src/test/data/db-3.json -o src/test/data/db-3-$TYPE-flatten.taskpaper -C -a "flatten $TYPE"
ofexport --log ofexport=ERROR -i src/test/data/db-3.json -o target/db-3-$TYPE-flatten.taskpaper -C -a "flatten $TYPE"
diff src/test/data/db-3-$TYPE-flatten.taskpaper target/db-3-$TYPE-flatten.taskpaper

TYPE=Task
################
echo -- $TYPE abbrieviated
################
ofexport --log ofexport=ERROR -i src/test/data/db-3.json -o target/db-3-$TYPE-flatten.taskpaper -t flatten
diff src/test/data/db-3-$TYPE-flatten.taskpaper target/db-3-$TYPE-flatten.taskpaper

TYPE=any
################
echo -- $TYPE
################
#ofexport --log ofexport=ERROR --open -i src/test/data/db-3.json -o src/test/data/db-3-$TYPE-flatten.taskpaper -a "flatten $TYPE"
ofexport --log ofexport=ERROR -i src/test/data/db-3.json -o target/db-3-$TYPE-flatten.taskpaper -a "flatten $TYPE"
diff src/test/data/db-3-$TYPE-flatten.taskpaper target/db-3-$TYPE-flatten.taskpaper

#---------------------------------------------------------------------

################
echo PRUNING TESTS
################

TYPE=Project
################
echo -- $TYPE
################
#ofexport --log ofexport=ERROR --open -i src/test/data/db-3.json -o src/test/data/db-3-$TYPE-prune.taskpaper -p prune
ofexport --log ofexport=ERROR -i src/test/data/db-3.json -o target/db-3-$TYPE-prune.taskpaper -p prune
diff src/test/data/db-3-$TYPE-prune.taskpaper target/db-3-$TYPE-prune.taskpaper

TYPE=Folder
################
echo -- $TYPE
################
#ofexport --log ofexport=ERROR --open -i src/test/data/db-3.json -o src/test/data/db-3-$TYPE-prune.taskpaper -f prune
ofexport --log ofexport=ERROR -i src/test/data/db-3.json -o target/db-3-$TYPE-prune.taskpaper -f prune
diff src/test/data/db-3-$TYPE-prune.taskpaper target/db-3-$TYPE-prune.taskpaper


TYPE=Context
################
echo -- $TYPE
################
#ofexport --log ofexport=ERROR --open -i src/test/data/db-3.json -o src/test/data/db-3-$TYPE-prune.taskpaper -C -c prune
ofexport --log ofexport=ERROR -i src/test/data/db-3.json -o target/db-3-$TYPE-prune.taskpaper -C -c prune
diff src/test/data/db-3-$TYPE-prune.taskpaper target/db-3-$TYPE-prune.taskpaper

#---------------------------------------------------------------------

################
echo SORTING TESTS
################

TYPE=Project
################
echo -- $TYPE
################
#ofexport --log ofexport=ERROR --open -i src/test/data/db-4.json -o src/test/data/db-4-$TYPE-sort.taskpaper -p "sort name"
ofexport --log ofexport=ERROR -i src/test/data/db-4.json -o target/db-4-$TYPE-sort.taskpaper -p "sort name"
diff src/test/data/db-4-$TYPE-sort.taskpaper target/db-4-$TYPE-sort.taskpaper

TYPE=Folder
################
echo -- $TYPE
################
#ofexport --log ofexport=ERROR --open -i src/test/data/db-4.json -o src/test/data/db-4-$TYPE-sort.taskpaper -f "sort name"
ofexport --log ofexport=ERROR -i src/test/data/db-4.json -o target/db-4-$TYPE-sort.taskpaper -f "sort name"
diff src/test/data/db-4-$TYPE-sort.taskpaper target/db-4-$TYPE-sort.taskpaper

TYPE=Context
################
echo -- $TYPE
################
#ofexport --log ofexport=ERROR --open -i src/test/data/db-4.json -o src/test/data/db-4-$TYPE-sort.taskpaper -C -c "sort name"
ofexport --log ofexport=ERROR -i src/test/data/db-4.json -o target/db-4-$TYPE-sort.taskpaper -C -c "sort name"
diff src/test/data/db-4-$TYPE-sort.taskpaper target/db-4-$TYPE-sort.taskpaper

TYPE=Project
################
echo -- $TYPE abbrieviated
################
ofexport --log ofexport=ERROR -i src/test/data/db-4.json -o target/db-4-$TYPE-sort.taskpaper -p sort
diff src/test/data/db-4-$TYPE-sort.taskpaper target/db-4-$TYPE-sort.taskpaper

#---------------------------------------------------------------------

################
echo FILTER TESTS
################

################
echo -- Folder
################
TEST=f1
#ofexport --log ofexport=ERROR -i src/test/data/db-1.json -o src/test/data/db-1-$TEST.taskpaper -a '(type=Folder) and (name="Sub Folder 1")'
ofexport --log ofexport=ERROR  -i src/test/data/db-1.json -o target/db-1-$TEST.taskpaper -a '(type=Folder) and (name="Sub Folder 1")'
diff src/test/data/db-1-$TEST.taskpaper target/db-1-$TEST.taskpaper

TEST=f2
#ofexport --log ofexport=ERROR -i src/test/data/db-1.json -o src/test/data/db-1-$TEST.taskpaper -a '(type=Folder) and (name="Sub Folder 2")'
ofexport --log ofexport=ERROR  -i src/test/data/db-1.json -o target/db-1-$TEST.taskpaper -a '(type=Folder) and (name="Sub Folder 2")'
diff src/test/data/db-1-$TEST.taskpaper target/db-1-$TEST.taskpaper

TEST=f3
#ofexport --log ofexport=ERROR --open -i src/test/data/db-1.json -o src/test/data/db-1-$TEST.taskpaper -a '(type=Folder) and (name=".*Folder 2")'
ofexport --log ofexport=ERROR  -i src/test/data/db-1.json -o target/db-1-$TEST.taskpaper -a '(type=Folder) and (name="Sub Folder 2")'
diff src/test/data/db-1-$TEST.taskpaper target/db-1-$TEST.taskpaper

TEST=f4
#ofexport --log ofexport=ERROR --open -i src/test/data/db-1.json -o src/test/data/db-1-$TEST.taskpaper -E -a '(type=Folder) and (name=".*Folder 2")'
ofexport --log ofexport=ERROR  -i src/test/data/db-1.json -o target/db-1-$TEST.taskpaper -E -a '(type=Folder) and (name=".*Folder 2")'
diff src/test/data/db-1-$TEST.taskpaper target/db-1-$TEST.taskpaper

################
echo -- Project
################
TEST=p1
#ofexport --log ofexport=ERROR --open -i src/test/data/db-1.json -o src/test/data/db-1-$TEST.taskpaper -a '(type=Project) and (name="F1 Project 1")'
ofexport --log ofexport=ERROR  -i src/test/data/db-1.json -o target/db-1-$TEST.taskpaper -a '(type=Project) and (name="F1 Project 1")'
diff src/test/data/db-1-$TEST.taskpaper target/db-1-$TEST.taskpaper

TEST=p2
#ofexport --log ofexport=ERROR --open -i src/test/data/db-1.json -o src/test/data/db-1-$TEST.taskpaper -a '(type=Project) and (name="F1 Project 2")'
ofexport --log ofexport=ERROR  -i src/test/data/db-1.json -o target/db-1-$TEST.taskpaper -a '(type=Project) and (name="F1 Project 2")'
diff src/test/data/db-1-$TEST.taskpaper target/db-1-$TEST.taskpaper

TEST=p3
#ofexport --log ofexport=ERROR --open -i src/test/data/db-1.json -o src/test/data/db-1-$TEST.taskpaper -a '(type=Project) and (name=".*1 Project 2")'
ofexport --log ofexport=ERROR  -i src/test/data/db-1.json -o target/db-1-$TEST.taskpaper -a '(type=Project) and (name=".*1 Project 2")'
diff src/test/data/db-1-$TEST.taskpaper target/db-1-$TEST.taskpaper

TEST=p4
#ofexport --log ofexport=ERROR --open -i src/test/data/db-1.json -o src/test/data/db-1-$TEST.taskpaper -E -a '(type=Project) and (name=".*1 Project 2")'
ofexport --log ofexport=ERROR  -i src/test/data/db-1.json -o target/db-1-$TEST.taskpaper -E -a '(type=Project) and (name=".*1 Project 2")'
diff src/test/data/db-1-$TEST.taskpaper target/db-1-$TEST.taskpaper

################
echo -- Task
################
TEST=t1
#ofexport --log ofexport=ERROR --open -i src/test/data/db-1.json -o src/test/data/db-1-$TEST.taskpaper -a '(type=Task) and (name="task F1 P1 1")'
ofexport --log ofexport=ERROR  -i src/test/data/db-1.json -o target/db-1-$TEST.taskpaper -a '(type=Task) and (name="task F1 P1 1")'
diff src/test/data/db-1-$TEST.taskpaper target/db-1-$TEST.taskpaper

TEST=t2
#ofexport --log ofexport=ERROR --open -i src/test/data/db-1.json -o src/test/data/db-1-$TEST.taskpaper -a '(type=Task) and (name="task F1 P1 2")'
ofexport --log ofexport=ERROR  -i src/test/data/db-1.json -o target/db-1-$TEST.taskpaper -a '(type=Task) and (name="task F1 P1 2")'
diff src/test/data/db-1-$TEST.taskpaper target/db-1-$TEST.taskpaper

TEST=t3
#ofexport --log ofexport=ERROR --open -i src/test/data/db-1.json -o src/test/data/db-1-$TEST.taskpaper -a '(type=Task) and (name=".*sk F1 P1 1")'
ofexport --log ofexport=ERROR  -i src/test/data/db-1.json -o target/db-1-$TEST.taskpaper -a '(type=Task) and (name=".*sk F1 P1 1")'
diff src/test/data/db-1-$TEST.taskpaper target/db-1-$TEST.taskpaper

TEST=t4
#ofexport --log ofexport=ERROR --open -i src/test/data/db-1.json -o src/test/data/db-1-$TEST.taskpaper -E -a '(type=Task) and (name="task F1 P1 2")'
ofexport --log ofexport=ERROR  -i src/test/data/db-1.json -o target/db-1-$TEST.taskpaper -E -a '(type=Task) and (name="task F1 P1 2")'
diff src/test/data/db-1-$TEST.taskpaper target/db-1-$TEST.taskpaper


################
echo -- Context
################
TEST=c1
#ofexport --log ofexport=ERROR --open -i src/test/data/db-1.json -o src/test/data/db-1-$TEST.taskpaper -C -a '(type=Context) and (name="Context 1")'
ofexport --log ofexport=ERROR  -i src/test/data/db-1.json -o target/db-1-$TEST.taskpaper -C -a '(type=Context) and (name="Context 1")'
diff src/test/data/db-1-$TEST.taskpaper target/db-1-$TEST.taskpaper

TEST=c2
#ofexport --log ofexport=ERROR --open -i src/test/data/db-1.json -o src/test/data/db-1-$TEST.taskpaper -C -a '(type=Context) and (name="Context 2")'
ofexport --log ofexport=ERROR  -i src/test/data/db-1.json -o target/db-1-$TEST.taskpaper -C -a '(type=Context) and (name="Context 2")'
diff src/test/data/db-1-$TEST.taskpaper target/db-1-$TEST.taskpaper

TEST=c3
#ofexport --log ofexport=ERROR --open -i src/test/data/db-1.json -o src/test/data/db-1-$TEST.taskpaper -C -a '(type=Context) and (name="Co.*ext 1")'
ofexport --log ofexport=ERROR  -i src/test/data/db-1.json -o target/db-1-$TEST.taskpaper -C -a '(type=Context) and (name="Co.*ext 1")'
diff src/test/data/db-1-$TEST.taskpaper target/db-1-$TEST.taskpaper

TEST=c4
#ofexport --log ofexport=ERROR --open -i src/test/data/db-1.json -o src/test/data/db-1-$TEST.taskpaper -C -E -a '(type=Context) and (name="Context 2")'
ofexport --log ofexport=ERROR  -i src/test/data/db-1.json -o target/db-1-$TEST.taskpaper -C -E -a '(type=Context) and (name="Context 2")'
diff src/test/data/db-1-$TEST.taskpaper target/db-1-$TEST.taskpaper

#---------------------------------------------------------------------

################
echo TESTING EXAMPLES
################

build-scripts/examples > /dev/null 

#---------------------------------------------------------------------

VERSION=`ofexport -? --log ofexport=ERROR | grep Version`
echo '###############################################################################'
echo "PASSED UNIT TESTS $VERSION"
echo '###############################################################################'


