#!/bin/bash

####################
# Run all the tests.
#
# If run with an argument then that argument is expected
# to be a file format and the tool tests are run in
# that format alone
####################

set -o xtrace
set -e

#########################################################
# Run some tests against a test folder in my OmniFocus DB
#########################################################

TEST_FOLDER="^Test"
TEST_CONTEXT="^Test"
INFILE=src/test/data/db-1.json

######################
echo INTEGRATION TESTS
#####################

function run_tool {

    FMT=$1
    MODE=$2
    SLEEP=0
    
    ###################'
    echo "-- $FMT $MODE"
    ###################'
    
	set +e
	mkdir -p target/$FMT
	set -e
	
	for TYPE in -t -f -p -c; do
	
	    # Be nice to my cpu fans...
        sleep $SLEEP; nice -20 python src/main/python/ofexport.py -i $INFILE -o target/$FMT/01$MODE$TYPE.$FMT $MODE -f="$TEST_FOLDER" > /dev/null
        sleep $SLEEP; nice -20 python src/main/python/ofexport.py -i $INFILE -o target/$FMT/02$MODE$TYPE.$FMT $MODE -f="$TEST_FOLDER" $TYPE=a > /dev/null
        sleep $SLEEP; nice -20 python src/main/python/ofexport.py -i $INFILE -o target/$FMT/03$MODE$TYPE.$FMT $MODE -f="$TEST_FOLDER" $TYPE!=a > /dev/null
        sleep $SLEEP; nice -20 python src/main/python/ofexport.py -i $INFILE -o target/$FMT/04$MODE$TYPE.$FMT $MODE -f="$TEST_FOLDER" $TYPE done="[this week]" > /dev/null
        sleep $SLEEP; nice -20 python src/main/python/ofexport.py -i $INFILE -o target/$FMT/05$MODE$TYPE.$FMT $MODE -f="$TEST_FOLDER" $TYPE done!="[this week]" > /dev/null
        sleep $SLEEP; nice -20 python src/main/python/ofexport.py -i $INFILE -o target/$FMT/06$MODE$TYPE.$FMT $MODE -f="$TEST_FOLDER" $TYPE due="[this week]" > /dev/null
        sleep $SLEEP; nice -20 python src/main/python/ofexport.py -i $INFILE -o target/$FMT/07$MODE$TYPE.$FMT $MODE -f="$TEST_FOLDER" $TYPE due!="[this week]" > /dev/null
        sleep $SLEEP; nice -20 python src/main/python/ofexport.py -i $INFILE -o target/$FMT/08$MODE$TYPE.$FMT $MODE -f="$TEST_FOLDER" $TYPE completed="[this week]" > /dev/null
        sleep $SLEEP; nice -20 python src/main/python/ofexport.py -i $INFILE -o target/$FMT/09$MODE$TYPE.$FMT $MODE -f="$TEST_FOLDER" $TYPE completed!="[this week]" > /dev/null
        sleep $SLEEP; nice -20 python src/main/python/ofexport.py -i $INFILE -o target/$FMT/10$MODE$TYPE.$FMT $MODE -f="$TEST_FOLDER" $TYPE start="[this week]" > /dev/null
        sleep $SLEEP; nice -20 python src/main/python/ofexport.py -i $INFILE -o target/$FMT/11$MODE$TYPE.$FMT $MODE -f="$TEST_FOLDER" $TYPE start!="[this week]" > /dev/null
        sleep $SLEEP; nice -20 python src/main/python/ofexport.py -i $INFILE -o target/$FMT/12$MODE$TYPE.$FMT $MODE -f="$TEST_FOLDER" $TYPE done="[this week]" > /dev/null
        sleep $SLEEP; nice -20 python src/main/python/ofexport.py -i $INFILE -o target/$FMT/13$MODE$TYPE.$FMT $MODE -f="$TEST_FOLDER" $TYPE done!="[this week]" > /dev/null
        sleep $SLEEP; nice -20 python src/main/python/ofexport.py -i $INFILE -o target/$FMT/14$MODE$TYPE.$FMT $MODE -f="$TEST_FOLDER" $TYPE due="[this week]" > /dev/null
        sleep $SLEEP; nice -20 python src/main/python/ofexport.py -i $INFILE -o target/$FMT/15$MODE$TYPE.$FMT $MODE -f="$TEST_FOLDER" $TYPE due!="[this week]" > /dev/null
        sleep $SLEEP; nice -20 python src/main/python/ofexport.py -i $INFILE -o target/$FMT/16$MODE$TYPE.$FMT $MODE -f="$TEST_FOLDER" $TYPE flagged > /dev/null
        sleep $SLEEP; nice -20 python src/main/python/ofexport.py -i $INFILE -o target/$FMT/17$MODE$TYPE.$FMT $MODE -f="$TEST_FOLDER" $TYPE !flagged > /dev/null
        sleep $SLEEP; nice -20 python src/main/python/ofexport.py -i $INFILE -o target/$FMT/18$MODE$TYPE.$FMT $MODE -f="$TEST_FOLDER" $TYPE sort > /dev/null
        sleep $SLEEP; nice -20 python src/main/python/ofexport.py -i $INFILE -o target/$FMT/19$MODE$TYPE.$FMT $MODE -f="$TEST_FOLDER" $TYPE sort=start > /dev/null
        sleep $SLEEP; nice -20 python src/main/python/ofexport.py -i $INFILE -o target/$FMT/20$MODE$TYPE.$FMT $MODE -f="$TEST_FOLDER" $TYPE sort=due > /dev/null
        sleep $SLEEP; nice -20 python src/main/python/ofexport.py -i $INFILE -o target/$FMT/21$MODE$TYPE.$FMT $MODE -f="$TEST_FOLDER" $TYPE sort=completed > /dev/null
        sleep $SLEEP; nice -20 python src/main/python/ofexport.py -i $INFILE -o target/$FMT/22$MODE$TYPE.$FMT $MODE -f="$TEST_FOLDER" $TYPE prune > /dev/null
        sleep $SLEEP; nice -20 python src/main/python/ofexport.py -i $INFILE -o target/$FMT/23$MODE$TYPE.$FMT $MODE -f="$TEST_FOLDER" $TYPE flat > /dev/null
        
    done
	
}

FMT=$1

if [ -z "$FMT" ]; then
    for FMT in tp md html opml ft json; do
        for MODE in -P -C; do
            run_tool $FMT $MODE
        done
    done
else
    run_tool $FMT -P
    run_tool $FMT -C
fi

VERSION=`ofexport | grep Version`
echo '###############################################################################'
echo "PASSED INTEGRATION TESTS $VERSION"
echo '###############################################################################'
