#!/bin/bash

set -o xtrace
set -e
export PYTHONPATH=`pwd`/src/main/python

################
# Run unit tests
################

python -m unittest discover -s src/test/python -p '*_test.py'

################
# Run diff tests
################

mkdir target

# Dump test folder as input to later tests
#build-scripts/dump-test-data --open -o src/test/data/db-1.json

# Re-write the test data in all formats
#ofexport -i src/test/data/db-1.json -o src/test/data/db-1.taskpaper
#ofexport -i src/test/data/db-1.json -o src/test/data/db-1.text
#ofexport -i src/test/data/db-1.json -o src/test/data/db-1.md
#ofexport -i src/test/data/db-1.json -o src/test/data/db-1.opml
#ofexport -i src/test/data/db-1.json -o src/test/data/db-1.html


ofexport -i src/test/data/db-1.json -o target/db-1.taskpaper
diff src/test/data/db-1.taskpaper target/db-1.taskpaper

ofexport -i src/test/data/db-1.json -o target/db-1.text
diff src/test/data/db-1.text target/db-1.text

ofexport -i src/test/data/db-1.json -o target/db-1.md
diff src/test/data/db-1.md target/db-1.md

ofexport -i src/test/data/db-1.json -o target/db-1.opml
diff src/test/data/db-1.opml target/db-1.opml

ofexport -i src/test/data/db-1.json -o target/db-1.html
diff src/test/data/db-1.html target/db-1.html

ofexport -i src/test/data/db-1.json -o target/db-1.json
diff src/test/data/db-1.json target/db-1.json

echo PASSED


