#!/bin/bash

set -o xtrace
set -e
export PYTHONPATH=`pwd`/src/main/python

################
# Run unit tests
################

python -m unittest discover -s src/test/python -p '*_test.py'

bash build-scripts/generate-todo

